default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: purchase_approval_app_development
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: localhost
  port: 5432

test:
  <<: *default
  database: purchase_approval_app_test
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: localhost
  port: 5432

# Credentials should never be hardcoded because sensitive information may be exposed if the source code is shared or committed to Git.
# Environment variables allow different credentials for each environment.

staging:
  <<: *default
  database: purchase_approval_app_staging
  username: <%= ENV["STAGING_DB_USERNAME"] %>
  password: <%= ENV["STAGING_DB_PASSWORD"] %>
  host: localhost
  port: 5432

production:
  primary: &primary_production
    <<: *default
    database: purchase_approval_app_production
    username: purchase_approval_app
    password: <%= ENV["PURCHASE_APPROVAL_APP_DATABASE_PASSWORD"] %>

  cache:
    <<: *primary_production
    database: purchase_approval_app_production_cache
    migrations_paths: db/cache_migrate

  queue:
    <<: *primary_production
    database: purchase_approval_app_production_queue
    migrations_paths: db/queue_migrate

  cable:
    <<: *primary_production
    database: purchase_approval_app_production_cable
    migrations_paths: db/cable_migrate